export const districts = [
  "Pune",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Chandigarh",
  "Bhopal",
  "Patna",
  "Kochi",
  "Guwahati",
  "Nagpur",
  "Indore",
  "Surat",
  "Vadodara",
  "Thane",
  "Satara",
  "Nashik",
  "Aurangabad",
  "Solapur",
  "Amravati",
]

export const practiceAreas = [
  "Civil Law",
  "Criminal Law",
  "Family Law",
  "Corporate Law",
  "Real Estate Law",
  "Intellectual Property",
  "Tax Law",
  "Labor Law",
  "Constitutional Law",
  "Environmental Law",
  "Immigration Law",
  "Bankruptcy Law",
  "Personal Injury",
  "Medical Malpractice",
  "Consumer Protection",
]
